// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: base_gcmessages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CSOEconItemAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefIndex   *uint32 `protobuf:"varint,1,opt,name=def_index,json=defIndex" json:"def_index,omitempty"`
	Value      *uint32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	ValueBytes []byte  `protobuf:"bytes,3,opt,name=value_bytes,json=valueBytes" json:"value_bytes,omitempty"`
}

func (x *CSOEconItemAttribute) Reset() {
	*x = CSOEconItemAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_gcmessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSOEconItemAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSOEconItemAttribute) ProtoMessage() {}

func (x *CSOEconItemAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_base_gcmessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSOEconItemAttribute.ProtoReflect.Descriptor instead.
func (*CSOEconItemAttribute) Descriptor() ([]byte, []int) {
	return file_base_gcmessages_proto_rawDescGZIP(), []int{0}
}

func (x *CSOEconItemAttribute) GetDefIndex() uint32 {
	if x != nil && x.DefIndex != nil {
		return *x.DefIndex
	}
	return 0
}

func (x *CSOEconItemAttribute) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *CSOEconItemAttribute) GetValueBytes() []byte {
	if x != nil {
		return x.ValueBytes
	}
	return nil
}

type CSOEconItemEquipped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewClass *uint32 `protobuf:"varint,1,opt,name=new_class,json=newClass" json:"new_class,omitempty"`
	NewSlot  *uint32 `protobuf:"varint,2,opt,name=new_slot,json=newSlot" json:"new_slot,omitempty"`
}

func (x *CSOEconItemEquipped) Reset() {
	*x = CSOEconItemEquipped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_gcmessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSOEconItemEquipped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSOEconItemEquipped) ProtoMessage() {}

func (x *CSOEconItemEquipped) ProtoReflect() protoreflect.Message {
	mi := &file_base_gcmessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSOEconItemEquipped.ProtoReflect.Descriptor instead.
func (*CSOEconItemEquipped) Descriptor() ([]byte, []int) {
	return file_base_gcmessages_proto_rawDescGZIP(), []int{1}
}

func (x *CSOEconItemEquipped) GetNewClass() uint32 {
	if x != nil && x.NewClass != nil {
		return *x.NewClass
	}
	return 0
}

func (x *CSOEconItemEquipped) GetNewSlot() uint32 {
	if x != nil && x.NewSlot != nil {
		return *x.NewSlot
	}
	return 0
}

type CSOEconItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *uint64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AccountId     *uint32                 `protobuf:"varint,2,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Inventory     *uint32                 `protobuf:"varint,3,opt,name=inventory" json:"inventory,omitempty"`
	DefIndex      *uint32                 `protobuf:"varint,4,opt,name=def_index,json=defIndex" json:"def_index,omitempty"`
	Quantity      *uint32                 `protobuf:"varint,5,opt,name=quantity,def=1" json:"quantity,omitempty"`
	Level         *uint32                 `protobuf:"varint,6,opt,name=level,def=1" json:"level,omitempty"`
	Quality       *uint32                 `protobuf:"varint,7,opt,name=quality,def=4" json:"quality,omitempty"`
	Flags         *uint32                 `protobuf:"varint,8,opt,name=flags,def=0" json:"flags,omitempty"`
	Origin        *uint32                 `protobuf:"varint,9,opt,name=origin,def=0" json:"origin,omitempty"`
	Attribute     []*CSOEconItemAttribute `protobuf:"bytes,12,rep,name=attribute" json:"attribute,omitempty"`
	InteriorItem  *CSOEconItem            `protobuf:"bytes,13,opt,name=interior_item,json=interiorItem" json:"interior_item,omitempty"`
	InUse         *bool                   `protobuf:"varint,14,opt,name=in_use,json=inUse,def=0" json:"in_use,omitempty"`
	Style         *uint32                 `protobuf:"varint,15,opt,name=style,def=0" json:"style,omitempty"`
	OriginalId    *uint64                 `protobuf:"varint,16,opt,name=original_id,json=originalId,def=0" json:"original_id,omitempty"`
	EquippedState []*CSOEconItemEquipped  `protobuf:"bytes,18,rep,name=equipped_state,json=equippedState" json:"equipped_state,omitempty"`
}

// Default values for CSOEconItem fields.
const (
	Default_CSOEconItem_Quantity   = uint32(1)
	Default_CSOEconItem_Level      = uint32(1)
	Default_CSOEconItem_Quality    = uint32(4)
	Default_CSOEconItem_Flags      = uint32(0)
	Default_CSOEconItem_Origin     = uint32(0)
	Default_CSOEconItem_InUse      = bool(false)
	Default_CSOEconItem_Style      = uint32(0)
	Default_CSOEconItem_OriginalId = uint64(0)
)

func (x *CSOEconItem) Reset() {
	*x = CSOEconItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_gcmessages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSOEconItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSOEconItem) ProtoMessage() {}

func (x *CSOEconItem) ProtoReflect() protoreflect.Message {
	mi := &file_base_gcmessages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSOEconItem.ProtoReflect.Descriptor instead.
func (*CSOEconItem) Descriptor() ([]byte, []int) {
	return file_base_gcmessages_proto_rawDescGZIP(), []int{2}
}

func (x *CSOEconItem) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CSOEconItem) GetAccountId() uint32 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *CSOEconItem) GetInventory() uint32 {
	if x != nil && x.Inventory != nil {
		return *x.Inventory
	}
	return 0
}

func (x *CSOEconItem) GetDefIndex() uint32 {
	if x != nil && x.DefIndex != nil {
		return *x.DefIndex
	}
	return 0
}

func (x *CSOEconItem) GetQuantity() uint32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return Default_CSOEconItem_Quantity
}

func (x *CSOEconItem) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return Default_CSOEconItem_Level
}

func (x *CSOEconItem) GetQuality() uint32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return Default_CSOEconItem_Quality
}

func (x *CSOEconItem) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return Default_CSOEconItem_Flags
}

func (x *CSOEconItem) GetOrigin() uint32 {
	if x != nil && x.Origin != nil {
		return *x.Origin
	}
	return Default_CSOEconItem_Origin
}

func (x *CSOEconItem) GetAttribute() []*CSOEconItemAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *CSOEconItem) GetInteriorItem() *CSOEconItem {
	if x != nil {
		return x.InteriorItem
	}
	return nil
}

func (x *CSOEconItem) GetInUse() bool {
	if x != nil && x.InUse != nil {
		return *x.InUse
	}
	return Default_CSOEconItem_InUse
}

func (x *CSOEconItem) GetStyle() uint32 {
	if x != nil && x.Style != nil {
		return *x.Style
	}
	return Default_CSOEconItem_Style
}

func (x *CSOEconItem) GetOriginalId() uint64 {
	if x != nil && x.OriginalId != nil {
		return *x.OriginalId
	}
	return Default_CSOEconItem_OriginalId
}

func (x *CSOEconItem) GetEquippedState() []*CSOEconItemEquipped {
	if x != nil {
		return x.EquippedState
	}
	return nil
}

var File_base_gcmessages_proto protoreflect.FileDescriptor

var file_base_gcmessages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x67, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x22, 0x6a,
	0x0a, 0x14, 0x43, 0x53, 0x4f, 0x45, 0x63, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x66, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x13, 0x43, 0x53,
	0x4f, 0x45, 0x63, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6e, 0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x92, 0x04, 0x0a, 0x0b, 0x43, 0x53,
	0x4f, 0x45, 0x63, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x66, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x31, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x17, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x3a, 0x01, 0x31, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x07, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x34, 0x52,
	0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x12, 0x19, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x39, 0x0a, 0x09,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x43, 0x53, 0x4f, 0x45, 0x63, 0x6f, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x09, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x69, 0x6f, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x43, 0x53, 0x4f, 0x45, 0x63, 0x6f, 0x6e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x1c, 0x0a, 0x06, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08,
	0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30,
	0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x04, 0x3a, 0x01, 0x30, 0x52,
	0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0e, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x12, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x43, 0x53, 0x4f, 0x45,
	0x63, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x52,
	0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x0c,
	0x48, 0x01, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x80, 0x01, 0x00,
}

var (
	file_base_gcmessages_proto_rawDescOnce sync.Once
	file_base_gcmessages_proto_rawDescData = file_base_gcmessages_proto_rawDesc
)

func file_base_gcmessages_proto_rawDescGZIP() []byte {
	file_base_gcmessages_proto_rawDescOnce.Do(func() {
		file_base_gcmessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_gcmessages_proto_rawDescData)
	})
	return file_base_gcmessages_proto_rawDescData
}

var file_base_gcmessages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_base_gcmessages_proto_goTypes = []interface{}{
	(*CSOEconItemAttribute)(nil), // 0: mango.CSOEconItemAttribute
	(*CSOEconItemEquipped)(nil),  // 1: mango.CSOEconItemEquipped
	(*CSOEconItem)(nil),          // 2: mango.CSOEconItem
}
var file_base_gcmessages_proto_depIdxs = []int32{
	0, // 0: mango.CSOEconItem.attribute:type_name -> mango.CSOEconItemAttribute
	2, // 1: mango.CSOEconItem.interior_item:type_name -> mango.CSOEconItem
	1, // 2: mango.CSOEconItem.equipped_state:type_name -> mango.CSOEconItemEquipped
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_base_gcmessages_proto_init() }
func file_base_gcmessages_proto_init() {
	if File_base_gcmessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_gcmessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSOEconItemAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_gcmessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSOEconItemEquipped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_gcmessages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSOEconItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_gcmessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_gcmessages_proto_goTypes,
		DependencyIndexes: file_base_gcmessages_proto_depIdxs,
		MessageInfos:      file_base_gcmessages_proto_msgTypes,
	}.Build()
	File_base_gcmessages_proto = out.File
	file_base_gcmessages_proto_rawDesc = nil
	file_base_gcmessages_proto_goTypes = nil
	file_base_gcmessages_proto_depIdxs = nil
}
